Algoritmo "terceiroAlg"
    //2)Escreva um algoritmo para ler as dimensões de um retângulo e calcular a área

Var
    numAltura, numBase, numArea : real

Inicio
    escreval("Digite a base do retangulo: ")
    leia(numBase)
    escreval("Digite a altura do triangulo: ")
    leia(numAltura)

    numArea <- numBase * numAltura

    escreval("A área do retangulo de base ", numBase, " e altura ", numAltura, " é: ", numArea)

Fimalgoritmo