Algoritmo "sextoAlg"
    //3) faça um algoritmo que leia a idade de uma pessoa expressa em anos, meses e dias e escreva a idade dessa pessoa expressa em dias. Considerar ano com 365 dias e mês com 30 dias

Var
    ano1 

Inicio
    funcao idade(ano : real, mes, dia : inteiro)
        var
            ano, mes, dia : real
        inicio

    fimFuncao

    escreval("Digite sua idade em 'anos + meses + dias' para saber quanto de cada um você já 'sobreviveu'")

Fimalgoritmo